version: "3.4"
services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - 4000:4000
    restart: on-failure
    depends_on:
      - database
    networks:
      - apidb
    command: ["refresh", "run"]
    tty: true
    env_file: .env

  database:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=ghuser
      - POSTGRES_PASSWORD=ghpassword
      - POSTGRES_DB=greenhouse
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - apidb

volumes:
  database_postgres:

networks:
  apidb:
    driver: bridge
