// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package gsql

import mock "github.com/stretchr/testify/mock"

// MockTransactionPool is an autogenerated mock type for the TransactionPool type
type MockTransactionPool struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *MockTransactionPool) Start() (Atomic, error) {
	ret := _m.Called()

	var r0 Atomic
	if rf, ok := ret.Get(0).(func() Atomic); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Atomic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
